"""Render results/tables.md from the results/*.json files written by sim012.py and stress.py."""
import json
from pathlib import Path

R = Path(__file__).resolve().parent / "results"


def load(name):
    p = R / name
    return json.loads(p.read_text()) if p.exists() else None


def f(x, fmt="{:.1f}"):
    return "-" if x is None else fmt.format(x)


out = ["# Debate 012 prototype results", "",
       "Generated by `make_tables.py` from `results/*.json` (`sim012.py`, `stress.py`). All runs use the scratch model",
       "`trip012.py`; with its default config it reproduces `src/trip.py` exactly (`check_parity.py`: 200/200 races).",
       "Every figure is Trip's server state at 10 Hz before the far-turn lock, over all 8 course x distance cells.", ""]

LABEL = {
    "D054": "D-054 as built (linear 0.6 s)",
    "D054+gap": "D-054 + 0.5 s reverse gap",
    "E10raw": "Eased 1.0 s, no anti-zig-zag rules",
    "E09": "Eased 0.8 s, chain, 0.4 s gap",
    "E10": "Eased 1.0 s, chain, 0.5 s gap",
    "E10refuse": "Eased 1.0 s, chain, 0.5 s gap, opposite presses refused",
    "E12": "Eased 1.1 s, chain, 0.8 s gap",
    "E09w": "Eased 0.8 s, chain, 0.4 s gap, weave gap 2.5 s",
    "E10w": "**Eased 1.0 s, chain, 0.5 s gap, weave gap 2.5 s (recommended)**",
}

m = load("e1_motion.json")
if m:
    out += ["## E1. Motion and zig-zag", "",
            "80 races per cell; one focal rider among 7 bots, per policy. Sideways speed and acceleration are over every horse",
            "(bots included) while it moves. Masher = 4 presses a second on a random side; ditherer = In, Out, In, Out every 0.2 s.", "",
            "| Variant | One lane | Two lanes | Masher reversals/min (shortest gap s) | Ditherer reversals/min (shortest gap s) | Casual reversals/min | Top sideways ft/s | Max drift | Speed p95 | Accel p95 ft/s² | Accel max ft/s² | Overlap frames |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for v, r in m.items():
        a = r["all_horses"]
        ov = sum(r[p]["overlaps"] for p in ("masher", "dither", "scripted", "rail"))
        out.append(f"| {LABEL.get(v, v)} | {f(r['one_lane_seconds'])} s | {f(r['two_lane_seconds'])} s | "
                   f"{r['masher']['reversals_per_min']:.1f} ({f(r['masher']['min_reversal_gap'])}) | "
                   f"{r['dither']['reversals_per_min']:.1f} ({f(r['dither']['min_reversal_gap'])}) | "
                   f"{r['scripted']['reversals_per_min']:.2f} | {a['vmax_ftps']:.1f} | {a['max_drift_deg']:.1f}° | "
                   f"{a['v_p95']:.1f} | {a['a_p95']:.0f} | {a['amax_ftps2']:.0f} | {ov} |")
    out.append("")

s = load("stress.json")
if s:
    out += ["## E1b. Overlap and jerk stress", "",
            "500 races per cell (4,000 per row); three riders press at once (masher, ditherer, casual) among five bots.",
            "Overlap = two horses within half a lane and 6 ft (the repo's overlap rule).", "",
            "| Variant / press rule / brush rule | Races | Races with an overlap | Overlap frames | Closest pair within 0.9 lane (ft) | Fastest fall-back (ft/s) |",
            "| --- | --- | --- | --- | --- | --- |"]
    for k, a in s.items():
        out.append(f"| {k} | {a['races']} | {a['overlap_races']} | {a['overlap_frames']} | {a['min_gap']:.2f} | {a['back_max']:.1f} |")
    out += ["", "E10 = eased 1.0 s with a 0.5 s gap but no weave gap and no glide reserve; E10w0 = weave gap, no reserve;",
            "E10w = weave gap + 6 ft glide reserve (recommended).", ""]


def boxed_table(b, title):
    out.append(f"### {title}")
    out.append("")
    out.append("| Policy | Boxed (share of pre-lock time) | Races boxed ≥ 1 s | Trapped (boxed, no tuck slot) | Inward reach ≤ 3 s | Free at press | Blocked at press ≤ 3 s / ≤ 5 s | Blocked share of inward presses |")
    out.append("| --- | --- | --- | --- | --- | --- | --- | --- |")
    for pol in ("smart_kid", "rail", "never", "scripted"):
        r = b[pol]
        re = r["reach"]
        q = lambda a, c: f"{a / c:.0%}" if c else "-"
        out.append(f"| {pol} | {r['boxed_share']:.1%} | {r['races_boxed_1s']:.0%} | {r['trapped_share']:.2%} | {q(re['ok3'], re['n'])} | "
                   f"{q(re['free_ok3'], re['free_n'])} | {q(re['blk_ok3'], re['blk_n'])} / {q(re['blk_ok5'], re['blk_n'])} | {q(re['blk_n'], re['n'])} |")
    out.append("")
    out.append("Boxed share by post 1–8: " + "; ".join(
        f"{pol} " + " ".join(f"{x['boxed_share']:.0%}" for x in b[pol]["by_post"]) for pol in ("smart_kid", "rail")))
    out.append("")
    out.append("Mean lane at the lock by post 1–8: " + "; ".join(
        f"{pol} " + " ".join(f"{x['lock_lane']:.1f}" for x in b[pol]["by_post"]) for pol in ("smart_kid", "rail")))
    out.append(f"Bots boxed: {b['bots_boxed_share']:.1%} of pre-lock time.")
    out.append("")


bx = load("e2_boxed.json")
if bx:
    out += ["## E2. Boxed in", "",
            "Motion E10w. One focal horse at each post among 7 bots, 25 races per cell per policy. Boxed = a horse within 12 ft ahead",
            "in your lane AND the inside blocked (rail, or a horse in the 8 ft-ahead / 10 ft-behind clear zone) AND the outside blocked.", ""]
    names = {"d054": "D-054 press handling (inward tucks at once, outward waits 1 s)",
             "wait+tuck": "Wait for a gap 1.5 s both ways, inward tucks at once",
             "wait+tuck0.5": "Wait 1.5 s, inward tucks after 0.5 s",
             "wait-only": "Wait 1.5 s, no tuck-back"}
    for k, b in bx.items():
        boxed_table(b, names.get(k, k))
bx3 = load("e2_boxed_E10w_wait3ptuck_wait3ptuck0.5.json")
if bx3:
    for k, b in bx3.items():
        boxed_table(b, {"wait3+tuck": "Wait 1.5 s out / 3 s in, inward tucks at once (recommended)",
                        "wait3+tuck0.5": "Wait 1.5 s out / 3 s in, tuck after 0.5 s"}.get(k, k))

for bname, btitle in (("e3_bumps.json", "inward presses dropped after 1.5 s (as shown to the panel)"),
                      ("e3_bumps_E10w_waitinfptuck.json", "final press rule (inward presses wait for room)")):
  bm = load(bname)
  if bm:
      out += [f"## E3. Brushes: {btitle}", "",
              "Motion E10w, wait + tuck. 60 races per cell. A brush never replaces a tuck-back the press could start, and the blocker",
              "must have been alongside (within 8 ft lengthwise in the next lane) for 0.3 s.", "",
              "| Trigger (cost) | Policy | Presses/race | Brushes/race | Races with a brush | Races charged | Mean cost | p95 cost | Max cost |",
              "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
      trig = {"repeat(eng)": "Second press while waiting (0.005, cap 2)",
              "any(comp)": "Any press at a horse alongside (0.002, 1 free, cap 3)",
              "repeat(comp)": "Second press while waiting (0.002, 1 free, cap 3)",
              "repeat2s": "**Second press within 2 s while waiting (0.002, 1 free, cap 3; recommended)**"}
      for bv, row in bm.items():
          for pol, r in row.items():
              out.append(f"| {trig.get(bv, bv)} | {pol} | {r['presses_per_race']:.0f} | {r['brushes_per_race']:.2f} | {r['races_with_brush']:.1%} | "
                         f"{r['races_charged']:.1%} | {r['mean_cost']:.4f} | {r['p95_cost']:.3f} | {r['max_cost']:.3f} |")
      out.append("")


def grief_table(g, title):
    out.append(f"### {title}")
    out.append("")
    out.append("| Motion / press rule / brush rule / kid | Strangers | Kid τ change | Kid own-trip change | Own-trip p5 | Races own-trip < −0.005 | Kid lane at lock | Kid charged bumps/race | Strangers charged bumps/race |")
    out.append("| --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    for key, row in g.items():
        for name, r in row.items():
            if name in ("control", "matched-bots"):
                continue
            out.append(f"| {key} | {name} | {r['delta_vs_matched_bots']:+.4f} | {r.get('own_trip_delta', float('nan')):+.4f} | "
                       f"{r.get('own_trip_delta_p5', float('nan')):+.4f} | {r.get('own_trip_share_below_-0.005', float('nan')):.1%} | "
                       f"{r['kid_lock_lane']:.2f} | {r['kid_bumps_per_race']:.2f} | {r['griefer_bumps_per_race']:.2f} |")
    out.append("")


g = load("e4_grief.json")
gc = load("e4_grief_controls.json")
gf = load("e4_grief_final.json")
if g or gc:
    out += ["## E4. Griefing", "",
            "Worst case: the strangers' skill targets equal the kid's (they tapped exactly like the kid), so they sit right beside it.",
            "40 races per cell. Changes are against the same strangers riding plain Smart Steer at the same pace (`matched-bots`).",
            "Own trip = the kid's ground + draft − its own bump charge (what a stranger could directly damage); τ also moves with",
            "the field mean. shadow = sits on the kid's inside; crew = three friends inside, outside and ahead; bumper = gets",
            "beside the kid and keeps pressing into it; rail1 / rail3 = the same matched strangers riding for the rail, not",
            "targeting anyone (the untargeted control).", ""]
    if gf:
        grief_table(gf, "Final rules (inward presses wait for room; brushes on a second press within 2 s), mover pays vs bumped pays")
    if gc:
        grief_table(gc, "With untargeted controls")
    if g:
        grief_table(g, "All press rules and who-pays options")

for rname in ("reach.json", "reach_final.json"):
  rc = load(rname)
  if rc:
      out += ["## E2b. Inward-press reach by press rule (follow-up sweep" + (", final rules with brushes)" if "final" in rname else ")"), "",
              "150 races per cell, a casual rider and a rail rider among 7 bots (E5's report seeds). all = every inward press within",
              "3 s (D-054's metric); first = presses with no press by that rider in the 3 s before (per intent); serv = the lane had",
              "room or a tuck slot at the press; waits = presses still waiting after 1 s with no glide and no tuck-back, per race",
              "(before the chip's 10 s limit). waitinf = an inward press waits until room (as D-054); wait3 = it drops after 3 s.", "",
              "| Motion / press rule | Cell | Casual all | Casual first | Casual serv | Casual waits/race | Rail all | Rail first |",
              "| --- | --- | --- | --- | --- | --- | --- | --- |"]
      for key, cells in rc.items():
          for cell, row in cells.items():
              c, r = row["scripted"], row["rail"]
              q = lambda a, b: f"{a / b:.0%}" if b else "-"
              out.append(f"| {key} | {cell} | {q(c['ok3'], c['n'])} | {q(c['first_ok3'], c['first_n'])} | {q(c['serv_ok3'], c['serv_n'])} | "
                         f"{c['chip'] / c['races']:.2f} | {q(r['ok3'], r['n'])} | {q(r['first_ok3'], r['first_n'])} |")
      out.append("")

for name, label in (("e5_accept_D054.json", "D-054 as built (checked-in baseline)"),
                    ("e5_accept_E10w_waitinf+tuck_repeatcomp.json", "Recommended motion and press rules, brushes on (second press, without the 2 s window). The τ targets don't depend on the window: rail riders, Smart Steer, never-steer riders and bots never brush. Reach with the window: E2b final"),
                    ("e5_accept_E09w_waitinf+tuck_repeatcomp.json", "Alternative glide 0.8 s (same rules)"),
                    ("e5_accept_E10w_wait3+tuck_off.json", "Eased 1.0 s, inward presses dropped after 3 s, no brushes (superseded)")):
    e = load(name)
    if not e:
        continue
    out += [f"## E5. Acceptance targets: {label}", "",
            f"Baseline races per cell and post: {e['baseline_races']}; report races per cell: {e['report_races']}.", "", "```", e["text"], "```", ""]
    out.append("Inward-press reach, alternative counts (casual rider / rail rider), per cell:")
    out.append("")
    out.append("| Cell | Casual: all presses ≤ 3 s | Casual: first presses (none in the 3 s before) | Casual: presses with room or a tuck slot | Casual 'wait for a gap' chips per press | Rail: all ≤ 3 s | Rail bumps/race | Casual bumps/race |")
    out.append("| --- | --- | --- | --- | --- | --- | --- | --- |")
    for x in e["extra"]:
        c, rr = x["casual"], x["rail"]
        q = lambda a, b: f"{a / b:.0%}" if b else "-"
        out.append(f"| {' '.join(x['cell'])} | {q(c['ok3'], c['n'])} | {q(c.get('first_ok3', 0), c.get('first_n', 0))} | "
                   f"{q(c.get('serv_ok3', 0), c.get('serv_n', 0))} | {q(c.get('chip', 0), c.get('presses', 0))} | {q(rr['ok3'], rr['n'])} | "
                   f"{x['rail_bumps']:.2f} | {x['casual_bumps']:.2f} |")
    out.append("")

(R / "tables.md").write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"wrote {R / 'tables.md'} ({len(out)} lines)")
