#!/usr/bin/env python3
"""Pack the in-game UI PNGs into 1024 px sheets for one Roblox upload each.

Reads assets/ui/png/<name>.png (rendered at 2x), scales each to half size, shelf-packs
them into as many 1024 x 1024 sheets as needed (Roblox stores images at 1024 max), and
writes assets/ui/atlas/ui_atlas_<n>.png plus game/src/shared/UiAtlas.luau (name ->
sheet, x, y, w, h). Particle textures (fx_*) and unused variants stay out: particles
need their own image ids.

  python tools/ui/build_atlas.py
"""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "assets" / "ui" / "png"
OUT = ROOT / "assets" / "ui" / "atlas"
LUAU = ROOT / "game" / "src" / "shared" / "UiAtlas.luau"
SHEET = 1024
PAD = 2
SCALE = 0.5

# What the client uses. Keep in sync with game/src/client/RaceController.client.luau.
NAMES = (
    ["hoof", "hoof_ring", "giddyup_pad", "giddyup_pad_pressed", "burst_bar", "burst_glow", "burst_marker", "burst_rays",
     "you_marker", "chance_up", "chance_down", "lane_sparkle", "finish_checker"]
    + [f"label_{k}" for k in ("perfect", "great", "good", "okay", "miss", "steady")]
    + [f"ribbon_{c}" for c in ("blue", "red", "yellow", "white")]
    + [f"lane_{i}" for i in range(1, 9)]
    + [f"lane_{i}_sparkle" for i in range(1, 9)]
)


def pack(images: dict[str, Image.Image]) -> list[dict[str, tuple[int, int, int, int]]]:
    """Shelf packing, tallest first. Returns one {name: (x, y, w, h)} per sheet."""
    order = sorted(images, key=lambda n: (-images[n].height, -images[n].width, n))
    sheets: list[dict[str, tuple[int, int, int, int]]] = [{}]
    x = y = shelf = 0
    for name in order:
        w, h = images[name].size
        if w > SHEET or h > SHEET:
            raise SystemExit(f"{name} is {w}x{h} after scaling, larger than a sheet")
        if x + w > SHEET:
            x, y, shelf = 0, y + shelf + PAD, 0
        if y + h > SHEET:
            sheets.append({})
            x = y = shelf = 0
        sheets[-1][name] = (x, y, w, h)
        x += w + PAD
        shelf = max(shelf, h)
    return sheets


def main() -> None:
    images = {}
    for name in NAMES:
        im = Image.open(SRC / f"{name}.png").convert("RGBA")
        images[name] = im.resize((max(1, round(im.width * SCALE)), max(1, round(im.height * SCALE))), Image.LANCZOS)
    sheets = pack(images)
    OUT.mkdir(parents=True, exist_ok=True)
    entries = {}
    for i, rects in enumerate(sheets, start=1):
        sheet_name = f"ui_atlas_{i}"
        height = max(y + h for (_, y, _, h) in rects.values())
        canvas = Image.new("RGBA", (SHEET, height), (0, 0, 0, 0))
        for name, (x, y, w, h) in rects.items():
            canvas.paste(images[name], (x, y))
            entries[name] = {"sheet": sheet_name, "x": x, "y": y, "w": w, "h": h}
        canvas.save(OUT / f"{sheet_name}.png", optimize=True)
        print(f"{sheet_name}.png  {SHEET}x{height}  {len(rects)} images")
    (OUT / "atlas.json").write_text(json.dumps(entries, indent=1, sort_keys=True) + "\n")
    lines = [
        "--!strict",
        "-- GENERATED by tools/ui/build_atlas.py: UI image name -> sheet and pixel rect. Do not edit by hand.",
        "-- Sheets are uploaded as Decals (tools/roblox/upload_assets.py, ids in UiImages); AssetService resolves",
        "-- each to an image id as ReplicatedStorage attribute UiSheet_<sheet>.",
        "export type Rect = { sheet: string, x: number, y: number, w: number, h: number }",
        "local UiAtlas: { [string]: Rect } = {",
    ]
    for name in sorted(entries):
        e = entries[name]
        lines.append(f'\t{name} = {{ sheet = "{e["sheet"]}", x = {e["x"]}, y = {e["y"]}, w = {e["w"]}, h = {e["h"]} }},')
    lines += ["}", "", "return UiAtlas", ""]
    LUAU.write_text("\n".join(lines))
    print(f"wrote {LUAU.relative_to(ROOT)} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
